aff_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aff_site.urls')),
]

aff_site/urls.py
from django.conf.urls import url
from django.urls import path
from aff_site import views
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from aff_site.api import ParticipantApi
#from django.views.generic import list_detail

#specify for URL Template tagging
app_name = 'aff_site'

urlpatterns = [
    url(r'^$',views.home, name = 'home'),
    url(r'^contacts/$',views.contacts, name = 'contacts'),
    url(r'^overview/$',views.overview, name ='overview' ),
    url(r'^login/$', views.user_login, name = 'user_login'),
    url(r'^logout/$', views.user_logout, name = 'user_logout'),
    url(r'^portal_landing/$', views.portal_landing, name = 'portal_landing'),
    url(r'^registration/$', views.register, name='register'),
    url(r'^signup/$', views.signup, name = 'signup'),
    url(r'^products/$', views.products, name = 'products'),
    url(r'^services/$', views.services, name = 'services'),
    url(r'^investors/$', views.investors, name = 'investors'),
    #url(r'^users_report/$', views.users_report, name = 'users_report'),
    #use @api_view decorator in views
    #url(r'^participantlist/$', views.participantlist, name = 'participantlist'),
    #use with class based view
    #url(r'^participantlist/$', ParticipantApi.as_view()),
    url(r'^participant/$', views.participant_list, name = 'participant_list'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

aff_site/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.utils import timezone
# Create your models here.

class Participant(models.Model):
    #participant_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length = 20)
    email = models.EmailField(max_length=50)
    #address = models.ForeignKey('Address', on_delete=models.CASCADE, blank=True, null=True) #automatically inserts _id at end of ForeignKey
    address = models.CharField(max_length=50, null = True)
    address2 = models.CharField(max_length=50, blank=True, null = True)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    comments = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add=True)

    #def __str__(self):
    #    return f'{self.last_name}, {self.first_name}, {self.email}, {self.address}, {self.city}, {self.country}'

    #def report_view(self, request):
    #    data = (self.user_report(user) for user in User.objects.all().order_by('first_name'))
    #    context = {'report': json.dumps(list(data))}
    #    return HttpResponse(render(request,
    #                           'admin/users_report.html',
    #                           context),
    #                    content_type='text/html')

class Meta:
    #managed = False
    db_table = 'participant'


class Portal_user(models.Model):

     #Create relationship (don't inherit from User!)
    #user = models.OneToOneField(User, on_delete=None)

    username = models.CharField(max_length=50, unique = True)
    email = models.EmailField(max_length=50, unique = True)
    password = models.CharField(max_length = 100)
    password2 = models.CharField(max_length = 100)

    def __str__(self):
        return self.username + " " + self.email + " " +self.password

class Meta:
    #managed = False
    db_table = 'portal_user'

'''
class Address(models.Model):
    #address_id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, blank=True, null = True)
    postal_code = models.CharField(max_length=10)
    #participant = models.ForeignKey('Participant', models.DO_NOTHING, blank=True, null=True)
    city = models.ForeignKey('City',on_delete=models.CASCADE, blank=True, null=True)
    #participant = models.ForeignKey('Participant', on_delete=models.CASCADE)
    class Meta:
        #managed = False  --this allows Django to create, modify and delete table
        db_table = 'address'


class City(models.Model):
    #city_id = models.AutoField(primary_key=True)
    city = models.CharField(max_length=50)
    country = models.ForeignKey('Country', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        #managed = False
        db_table = 'city'


class Country(models.Model):
    #country_id = models.AutoField(primary_key=True)
    country = models.CharField(max_length=50)

    class Meta:
        #managed = False
        db_table = 'country'
# Create your models here.
'''

aff_site/forms.py
from django import forms
from aff_site.models import Participant, Portal_user #,Address,City,Country
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewParticipant(forms.ModelForm):
    class Meta:
        model = Participant
        #exclude = ['address']
        fields = '__all__'

'''
class SignupForm(forms.ModelForm):
    class Meta:
        model = Portal_user
        widgets = {'password':forms.PasswordInput, 'password2':forms.PasswordInput}
        fields = '__all__'
'''
class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


'''class SignupForm(UserCreationForm):
    email = forms.EmailField(
        required=True, widget=forms.TextInput(attrs={'class':'form-control'})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    password1 = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'})
    )
    password2 = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'})
    )
'''

aff_site/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage

#from djano.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login, logout

#use REST framework with function based views
from rest_framework.decorators import api_view

from .forms import NewParticipant, SignupForm

#imports for populating django tables
from aff_site.models import Participant
from .tables import ParticipantTable
from django_tables2 import RequestConfig


def home(request):
    return render (request, 'aff_site/main_page.html')

def contacts(request):
    return render (request, 'aff_site/contacts.html')

def overview(request):
    return render (request, 'aff_site/overview.html')

def products(request):
    return render (request, 'aff_site/products.html')

def services(request):
    return render (request, 'aff_site/services.html')

def investors(request):
    return render (request, 'aff_site/investors.html')

def participant_list(request):
    table = ParticipantTable(Participant.objects.all())

    return render(request, 'participant_list.html', {
    'table': table
    })

#def registered_list(request):
#    return render (request, 'aff_site/registered_list.html')
#@api_view()
#def participantlist(request):
#    return render (request, 'aff_site/users_report.html')

@login_required
def portal_landing(request):
    return render (request, 'aff_site/portal_landing.html')

def user_login(request):

    if request.method == 'POST':
        #portal_user = Portal_user(request.POST or None)
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('aff_site:portal_landing'))

            else:
                return HttpResponse ("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse ("Login failed")
    else:
        return render(request, 'aff_site/user_login.html', {})

#use decorator to make sure that only a user logged in can have logout option
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('aff_site:home'))


def signup(request):
    portal_user = False
    if request.method == 'POST':
        PortaluserForm = SignupForm(request.POST)
#extras from here
        if PortaluserForm.is_valid(): #and address_form.is_valid() and city_form.is_valid() and country_form.is_valid():

            user = PortaluserForm.save(commit = False)
            user.is_active = False
            user.save()

            portal_user = True

            #return HttpResponse('Thanks for registering as a user. Kindly log in to the platform within the next 12 hrs')
            '''
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = PortaluserForm.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')'''
    else:
        PortaluserForm = SignupForm()
    #return render(request, 'signup.html', {'PortaluserForm': PortaluserForm})
    return render (request, 'aff_site/signup.html',
                                    {'PortaluserForm':PortaluserForm,
                                    'portal_user':portal_user})

            #hash the password
            #user.set_password(user.password)

            #user.save()

            #PortaluserForm.save()


            #return HttpResponseRedirect(reverse('aff_site:home'))
    #else:
    #    PortaluserForm = SignupForm()
    #return render (request, 'create_portal_user.html',
    #                            {'PortaluserForm':PortaluserForm})


#activate function
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


def register(request):

    registered = False

    if request.method == "POST":
        participant_form = NewParticipant(request.POST)
#extras from here
        if participant_form.is_valid(): #and address_form.is_valid() and city_form.is_valid() and country_form.is_valid():
            participant_form.save()

        registered = True
            #return HttpResponse("Thank you for registering for this event.")
            #return HttpResponseRedirect(reverse('aff_site:register'))
    else:
        #No HTTP request so just return a blank form
        participant_form = NewParticipant()

    # This is the render and context dictionary to feed
    # back to the registration.html file page
    return render (request, 'aff_site/registration.html',
                                {'participant_form':participant_form,
                                'registered':registered})
                                 #'address_form':address_form,

aff_site/templates/aff_site/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>AFF Site</title>
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" />
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <!--<nav class="navbar navbar-default navbar-static-top">-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav mr-auto">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'aff_site:home' %}">ALL FORECASTS FINANCIAL</a></li>

          <!-- <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li> -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item highlight">
                      <a class="nav-link" href="{% url 'aff_site:products' %}">Products <span class="sr-only">(current)</span></a>
                  </li>

                  <li class="nav-item " >
                      <a class="nav-link" href="{% url 'aff_site:services' %}">Services <span class="sr-only">(current)</span></a></li>

                  <li class="nav-item "><a class="nav-link" href="{% url 'aff_site:investors' %}">Investors</a></li>

                  {# Some logic to show Portal in navbar if user is logged on#}
                  {% if user.is_authenticated %}
                  <li class="nav-item active"><a class="nav-link" href="{% url 'aff_site:portal_landing' %}">Portal</a></li>
                  {% else %}
                  <li class="nav-item"><a class="nav-link disabled" href="#">Portal</a></li>
                  {% endif %}

                  <!--<li class="nav-item "><a class="nav-link" href="{% url 'aff_site:portal_landing' %}">Portal</a></li>-->
        <!--  <li><a class="navbar-link" href="{% url 'aff_site:user_login' %}">Login</a></li> -->
                  <li class="nav-item "><a class="nav-link" href="{% url 'aff_site:signup' %}">Register</a></li>

                  {# Some logic on what to display for last item#}
                  {% if user.is_authenticated %}
                  <li class="nav-item active"><a class="nav-link" href="{% url 'aff_site:user_logout' %}">Logout</a></li>
                  {% else %}
                  <li><a class="nav-link" href="{% url 'aff_site:user_login' %}">Login</a></li>
                  {% endif %}


              </ul>
          </div>
    </nav>
    <div class="container">
    {% block body_block %}

    {% endblock %}



  </body>
</html>

aff_site/templates/aff_site/contacts.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>All Forecasts Financial</title>
        {% load static %}
        

        <link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
        <!--<link rel="stylesheet" href="aff_site.css">-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    </head>
    <body>


    <div class="main-banner">
        <h1><em>AFF - All Forecasts Financial</em></h1>

    </div>

    <br>
    <div class="container">
    <!-- use a tags and css styling for buttons. insert hyperlinks for hrefs -->
    <a href="" class="button">Products</a>
    <a href="" class="button">Services</a>
    <a href="" class="button">Investors</a>
    <a href="{% url 'aff_site:user_login' %}" class="button">Login</a>

    <br>
    <br>

    <!--Use relative URL tagging-->
    <div class="myleftcolumn">
        <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

        <p><a href = "{% url 'aff_site:overview' %}">AFF Overview</a></p>

        <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>
    </div>

    <!--use "mailto" to let users email program open email with address already in it -->
    <div class="myrightcolumn">
        <center>
        <p>AFF is a great innovative company. Please click this link below to send us an email: </p>
        <p>Email:<a href = "mailto:heveljb@gmail.com"> heveljb@gmail.com</a></p>
        </center>

    </div>
    <br>

    <div id="footerbuttons">
        <a href="" style = "color: black;" class="button">About</a>
        <a href="{% url 'aff_site:contacts' %}" style = "color: black;" class="button">Contacts</a>
        <a href="" style = "color: black;" class="button">Help</a>

    </div>
    </div>

    </body>
</html>

aff_site/templates/aff_site/investors.html
{% extends 'aff_site/base.html' %}
{% load static %}
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}" >
{% block body_block %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
<div class="myleftcolumn">
    <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

    <p><a href = "{%url 'aff_site:overview' %}">AFF Overview</a></p>

    <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>

</div>

<div class="myrightcolumn">
    <p>Please check back soon for further information.</p>


</div>
<br>

{% endblock %}

<!---
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>All Forecasts Financial</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
        <!-<link rel="stylesheet" href="aff_site.css">-
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    </head>
    <body>


    <div class="main-banner">
        <h1>AFF - All Forecasts Financial</h1>

    </div>

    <br>
    <div class="container">
    <!- use a tags and css styling for buttons. insert hyperlinks for hrefs -
    <a href="" class="button">Products</a>
    <a href="" class="button">Services</a>
    <a href="" class="button">Investors</a>
    <a href="{% url 'aff_site:user_login' %}" class="button">Login</a>

    <br>
    <br>
    <!-insert links into href -
    <div class="myleftcolumn">
        <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

        <p><a href = "">AFF Overview</a></p>

        <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>
    </div>

    <div class="myrightcolumn">
        <p>AFF is a great innovative company that has the following units:</p>

        <ul>
            <li>Analytics</li>
            <li>Technology</li>
            <li>Financial</li>
            <li>AI - Artificial Intelligence</li>
            <li>And Others</li>
        </ul>
        <p> Please send us an  <a href = "mailto:heveljb@gmail.com">email</a> to request information about these services.</p>
    </div>
    <br>

    <div id="footerbuttons">
        <a href="" style = "color: black;" class="button">About</a>
        <a href="{% url 'aff_site:contacts' %}" style = "color: black;" class="button">Contacts</a>
        <a href="" style = "color: black;" class="button">Help</a>

    </div>
    </div>
    </body>
    </html>
-->

aff_site/templates/aff_site/main_page.html
{% extends 'aff_site/base.html' %}
{% load static %}
{% block body_block %}


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
<div class="myleftcolumn">
    <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

    <p><a href = "{%url 'aff_site:overview' %}">AFF Overview</a></p>

    <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>

</div>

<div class="myrightcolumn">
    <p>AFF is an innovative company that has the following units:</p>

    <ul>
        <li>Analytics</li>
        <li>Technology</li>
        <li>Financial Modeling</li>
        <li>AI - Artificial Intelligence</li>

    </ul>

</div>
<br>

{% endblock %}
<!--
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>All Forecasts Financial</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    </head>
    <body>


    <div class="main-banner">
        <h1>AFF - All Forecasts Financial</h1>

    </div>

    <br>
    <div class="container">
    -->
    <!-- use a tags and css styling for buttons. insert hyperlinks for hrefs -->

<!--
    <a href="" class="button">Products</a>
    <a href="" class="button">Services</a>
    <a href="" class="button">Investors</a>
    <a href="{% url 'aff_site:user_login' %}" class="button">Login</a>
    <a href="{% url 'aff_site:signup' %}" class="button">Sign Up</a>

    <br>
    <br>
    <!
    <button class="button" name="products">Products</button>
    <button class="button" name="services">Services</button>
    <button class="button" name="investors">Investors</button>
    <button class="button" name="login">Login</button>


    <!insert links into href -
    <div class="myleftcolumn">
        <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

        <p><a href = "{% url 'aff_site:overview' %}">AFF Overview</a></p>

        <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>


        <p><a href = "{% url 'aff_site:portal_landing' %}">User Portal</a></p>
    </div>

    <div class="myrightcolumn">


        <p>AFF is a great innovative company that has the following units:</p>

        <ul>
            <li>Analytics</li>
            <li>Technology</li>
            <li>Financial</li>
            <li>AI - Artificial Intelligence</li>
            <li>And Others</li>
        </ul>


    </div>
    <br>

    <div id="footerbuttons">
        <a href="" style = "color: black;" class="button">About</a>
        <a href="{% url 'aff_site:contacts' %}" style = "color: black;" class="button">Contacts</a>
        <a href="" style = "color: black;" class="button">Help</a>

    </div>
    </div>
    </body>
</html>
-->

aff_site/templates/aff_site/participant_list.html
{% load render_table from django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html">
    <head>
        <meta charset="utf-8">
        
        <link rel="stylesheet" href="{% static 'css/django_tables2.css' %}" type="text/css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <title>List of persons</title>
    </head>
    <body>
        <div class = container>
            {% block body %}
                {% render_table table %}
            {% endblock %}
        </div>
    </body>
</html>

aff_site/templates/aff_site/portal_landing.html
{% extends 'aff_site/base.html' %}
{% block body_block %}
    <br>
    <h2>Welcome to the AFF Portal.</h2>
    <br>
{% endblock %}

aff_site/templates/aff_site/users_report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>All Forecasts Financial</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/aff_site.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/ui-gridmin.css' %}" type="text/css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular-touch.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular-animate.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular-aria.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/lodash.min.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/jszip.min.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/excel-builder.dist.js"></script>


        <script src="{% static 'js/app.js' %}"></script>

    </head>
    <body>


    <div class="main-banner">
        <h1>AFF - All Forecasts Financial</h1>

    </div>

    <br>
    <div class="container">
    <!-- use a tags and css styling for buttons. insert hyperlinks for hrefs -->
    <a href="" class="button">Products</a>
    <a href="" class="button">Services</a>
    <a href="" class="button">Investors</a>
    <a href="{% url 'aff_site:user_login' %}" class="button">Login</a>
    <a href="{% url 'aff_site:signup' %}" class="button">Sign Up</a>

    <br>
    <br>
    <!--
    <button class="button" name="products">Products</button>
    <button class="button" name="services">Services</button>
    <button class="button" name="investors">Investors</button>
    <button class="button" name="login">Login</button>
    -->

    <!--insert links into href -->
    <div class="myleftcolumn">
        <p><a href = "{% url 'aff_site:home' %}">Home</a></p>

        <p><a href = "{% url 'aff_site:overview' %}">AFF Overview</a></p>

        <p><a href = "{% url 'aff_site:register' %}">Sign Up for Event</a></p>

        <p><a href = "{% url 'aff_site:users_report' %}">List of Users</a></p>

        <p><a href = "{% url 'aff_site:portal_landing' %}">User Portal</a></p>
    </div>

    <div class="myrightcolumn">


        <div ng-controller="MainCtrl as $ctrl">
          <div id="grid1" ui-grid="{ data: $ctrl.myData }" class="myGrid"></div>
        </div>


    </div>
    <br>

    <div id="footerbuttons">
        <a href="" style = "color: black;" class="button">About</a>
        <a href="{% url 'aff_site:contacts' %}" style = "color: black;" class="button">Contacts</a>
        <a href="" style = "color: black;" class="button">Help</a>

    </div>
    </div>
    </body>
</html>